### ISSUE TITLE
URL Handler to devices

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#15]
There should be a URL Handler to IP addresses in popups.

There should be links:
winbox://IP
mtr://IP
https://IP

So we can carry those links by browsers to specified program or use it by itself.
As a result, we do not need to type IP addresses for programs but we can open it by clicking icons and use browser url-handlers. If You are network device administrator this thing make Your work much simple.

![http](https://cloud.githubusercontent.com/assets/17087236/21887918/4eb4651e-d8c2-11e6-95ac-ab397822bae8.png)
![mtr](https://cloud.githubusercontent.com/assets/17087236/21887919/4eb5ef1a-d8c2-11e6-9e31-64a5300268ef.png)
![winbox](https://cloud.githubusercontent.com/assets/17087236/21887920/4eb6717e-d8c2-11e6-9e40-a02075b155ec.png)

It's easy to add that.

```
@@ -1142,6 +1148,17 @@ function ajax_status() {
                                <tr>
                                        <td style='vertical-align:top;'>" . __('Contact:') . "</td>
                                        <td style='vertical-align:top;'>" . $host['snmp_sysContact'] . "</td>
+                               </tr>
+                               <tr>
+                                       <td style='vertical-align:top;'><img src=./images/http.png></img> " . __('HTTP:') . "</td>
+                                       <td style='vertical-align:top;'>" . "<a href=https://".$host['hostname'] . ":5457 target=_blank>" . $host['hostname']."</a>" . "</td>
+                               </tr>
+                               <tr>
+                                       <td style='vertical-align:top;'><img src=./images/mtr.png></img> " . __('MTR:') . "</td>
+                                       <td style='vertical-align:top;'>" . "<a href=mtr:".$host['hostname'] . " target=_blank>" . $host['hostname']."</a>" . "</td>
+                               <tr>
+                                       <td style='vertical-align:top;'><img src=./images/winbox.png></img> " . __('Winbox:') . "</td>
']."</a>" . "</td>
                                </tr>":"") . "
                                </table>\n";
```

**Comment by interduo** [comment]
It could be better done by scenario:

Right Click on icon causes a list "CONNECT TO:"
- Winbox
- HTTP
- HTTPS

**Comment by cigamit** [comment]
Can you please create a pull request.

**Comment by cigamit** [comment]
Also, please publish a link to the license on those icons please.

**Comment by interduo** [comment]
I don't have a local cacti git repository So I send You a git diff.
Icons I did myself there is no license. You can use it free :\  
You can replace by them if you want.

**Comment by interduo** [comment]
Could You put this code into git?

**Comment by cigamit** [comment]
I'm still giving this some thought.  I would suggest that this feature does not go far enough.  It should also include:

- Autodetection of which URL handler to use by snmp_sysDescr, Device Template, or other meta data.
- Many people will load into Cacti meta information about their devices including lights-out ip addresses such as ipmi management addresses, rack location and enclosure number and slot
- That meta information can be used to create links inside of various Cacti pages.

So, to do this right, we need something like a Device meta plugin that allows people to define such things, and one of the meta columns could be a remote capabilities which could include winbox (for RouterOS), http[s], lights out address, etc.  Additionally, the display of that information has to be based upon permission.

What I'm trying to say is that it's not that I don't like this customization, but it does not go far enough for enterprise shops.  For now, you should keep your customization in place, but understand that I'm not merging because I don't like it, it's because it needs to be done differently.
