### ISSUE TITLE
Mute function

### ISSUE THREAD

**Issue by Matizmat** [Cacti/plugin_monitor#81]
We use Monitor plugin on a NOC to be alerted with sound about new down device.
We used an oldest version of cacti with monitor and the sound alert worked well. But since upgrade to he last version of cacti 1.2.1 and last plugins versions Monitor / thod (master then dev), we have a problem with the Mute functionality.
When a device is down, we use the mute button (investigate etc ...), but if a new device is down, sound stay muted.

Do you know if this is a normal situation ? Maybe i have forgot something !

Thansk a lot for your time :)

**Comment by netniV** [comment]
The mute functionality is based off device ids so should sound again when a new device goes offline. I will have to run some tests hopefully over the weekend but I would have thought others would have moaned if that wasn’t working since the code hasn’t changed in months. What version of monitor are you using? What version of thold?

**Comment by Matizmat** [comment]
Cacti Version | 1.2.1
Thold 1.0.3
Monitor 2.1
Try with Master version and develop

I will try to make a clean install to see if it's my installation !

**Comment by netniV** [comment]
Did you manage to see if it was resolved?

**Comment by cigamit** [comment]
It was still broken.  I'm fixing now.

**Comment by cigamit** [comment]
Resolved.

**Comment by Matizmat** [comment]
Hello,
Thanks a lot i'll update as soon as possible ;)
