### ISSUE TITLE
Enhancement: Allow custom sizing of devices and fonts

### ISSUE THREAD

**Issue by sam-chapp** [Cacti/plugin_monitor#92]
Is there something I can add because the formatting on my cacti is on default and when I edit the display settings they only change the graphs but not the actual monitor plugin

*** Updated with enhancement request info ***

**Describe the bug**
I cant manually change the design (eg. font size / placement of item )
![image](https://puu.sh/CSvkO/e5f0638f63.png)

as you see I have to zoom out to fit them all in and that means the font gets smaller

**Expected behavior**
I would like to be able to change the style also like to be able to manually move the boxes around

**Screenshots**
https://puu.sh/CSvkO/e5f0638f63.png

**Plugin (please complete the following information):**

* Version:2.3.4
* Source: github
* Identifer: ? 

**Desktop (please complete the following information):**

* OS: 10
* Browser chrome
* Version: ? latest

**Comment by netniV** [comment]
Can you explain a bit more what you are referring to and the steps?  When creating a new issue it's useful to follow the template to give as much information as possible.

**Comment by netniV** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Plugin (plreace complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by sam-chapp** [comment]
**Describe the bug**
I cant manually change the design (eg. font size / placement of item )
[https://puu.sh/CSvkO/e5f0638f63.png](url)
as you see I have to zoom out to fit them all in and that means the font gets smaller

**Expected behavior**
I would like to be able to change the style also like to be able to manually move the boxes around

**Screenshots**
https://puu.sh/CSvkO/e5f0638f63.png

**Plugin (plreace complete the following information):**

* Version:2.3.4
* Source: github
* Identifer: ? 

**Desktop (please complete the following information):**

* OS: 10
* Browser chrome
* Version: ? latest

**Comment by netniV** [comment]
OK, to resolve the question marks you had above:
* GitHub Identifier would be the latest commit you have.  At command line, you can see this via the first entry on `git log`.  If you are using the GitHub app, select the repository, then select the History tab (on the left) and the commit should visible in the main window

   ![image](https://user-images.githubusercontent.com/9052188/53503815-bc534000-3aa8-11e9-81ef-c0820b1510f9.png)

   ![image](https://user-images.githubusercontent.com/9052188/53503624-5070d780-3aa8-11e9-9739-1f901d81f67d.png)

* Chrome version can be found by clicking the three lines that represent it's menu, then Help -> About Chrome. Alternatively, you can just browse to chrome://settings/help

   ![image](https://user-images.githubusercontent.com/9052188/53503749-988ffa00-3aa8-11e9-86d0-4fdb358eb632.png)

As for being able to move hosts around, that would be an interesting feature.  Could you open that as a separate request since it's a completely different enhancement? (Copy and paste most of the above post, just make it about the drag/drop capability only).  It could be trickier when in those modes that display only triggered/breached hosts.

On the sizing front, that comes from the "Extra Small" setting you are currently using.  I think there are five different settings for size.  Due to various formatting issues, we haven't allowed for customisation of this before now.  It may be something we look to in the future but at the moment, you're only choice is to edit the CSS file.

**Comment by netniV** [comment]
Just for reference, I removed the three posts we made to get the full info and updated your original post with the detail you provided.

**Comment by sam-chapp** [comment]
I am in the plugin file atm where is the "extra small, small, medium, large" css files?

**Comment by netniV** [comment]
They are all part of the main CSS file: .monitor_exsmall* .monitor_small* .monitor_medium* .monitor_large* .monitor_exlarge*

**Comment by sam-chapp** [comment]
where is the main css file?

**Comment by sam-chapp** [comment]
?

**Comment by netniV** [comment]
In the same directory as the plugin.
